### ISSUE TITLE
Publish doesn't seem to work

### ISSUE THREAD

**Issue by plohm12** [Root16/bamboo#47]
---
Version: 0.2.2
Settings:
- Create Web Resource: Ask For Name = false
- Create Web Resource: Update If Exists = true
- General: List Files On Startup = false
- Upload Web Resource: Publish If Successful = true
---

Repro:
1. Setup bamboo.conf.json with the name of a fresh, empty solution and an existing web resource
  a. If the web resource is set in fileMappings, remove that mapping.
2. Modify and save your local file corresponding to an existing web resource using the default mapping & folder structure as the remote web resource name.
3. Right click the file and select "Create and upload webresource to Power Apps"
  a. Notification "Action: Update. Successful: true."
  b. Notification "Action: Publish. Successful: true."

I determined that the publish operation doesn't work in this case using the following steps:
1. Query the web resource table row via Web API and inspect the `content` column value by converting from Base64 string to binary and saving to file as "PUBLISHED_VERSION.js"
  a. Ex. `/api/data/v9.2/webresourceset?$select=content&$filter=name eq 'new_/my/webresource.js'`
2. Query the same table row via Web API, this time grabbing the unpublished version using the [RetrieveUnpublished](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/retrieveunpublished) function and again converting `content` from Base64 to binary and saving to file "UNPUBLISHED_VERSION.js"
  a. Ex. `api/data/v9.2/webresourceset(<GUID-FROM-PREVIOUS-QUERY>)/Microsoft.Dynamics.CRM.RetrieveUnpublished()`
3. View these two files in a text editor. PUBLISHED_VERSION.js contains the unchanged web resource, and UNPUBLISHED_VERSION.js contains the recent edits.

**Comment by johnyenter-briars** [comment]
@plohm12  Thank you for opening this ticket! I followed your reproduction steps and was able to confirm this is an issue. We will look into it!
